pipeline {
    agent { label 'WindowsAgent' }
    
stages {
	stage ('Checkout'){
		steps{
                echo 'Checkout .....'	
		checkout scm
	    }
	}
	stage('Build') {
            steps {
                echo 'Building..'
		bat 'nuget restore APPCOREFRAMEWORK.sln'
		bat "\"${tool 'msbuild'}\" APPCOREFRAMEWORK.sln /p:Configuration=Release /p:Platform=\"Any CPU\" /p:ProductVersion=1.0.0.${env.BUILD_NUMBER}"
            }
        }
        stage('Test') {
            steps {
                echo 'Testing....'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
				bat "\"${tool 'msbuild'}\" APPCOREFRAMEWORK.sln /p:DeployOnBuild=True /p:PublishProfile=FolderProfile"
            }
        }
	stage ('Archive'){
		steps{
		archive 'APPCOREFRAMEWORK/bin/**'
		archive 'APPCOREFRAMEWORK/Contents/**'
		archive 'APPCOREFRAMEWORK/scripts/**'
		archive 'APPCOREFRAMEWORK/Views/**'
		archive 'APPCOREFRAMEWORK/ApplicationInsights.config'
		archive 'APPCOREFRAMEWORK/Global.asax'
		archive 'APPCOREFRAMEWORK/packages.config'
		archive 'APPCOREFRAMEWORK/Web.config'
	        }
        }
        }
     post {
        always {
            echo 'Sending Email Notification'
            
            emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                recipientProviders: [[$class: 'DevelopersRecipientProvider'], [$class: 'RequesterRecipientProvider']],
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}"
            
        }
    }
  }
